### ISSUE TITLE
请教一下，这个项目部署在github上的使用了代理么

### ISSUE THREAD

**Issue by ddqre12345** [walleeeee/daily-zhihu#1]
我尝试了将build后的项目部署在github上，不过部分静态资源指向有问题，在本地用tomcat或者nginx代理就不存在相应问题，我想请问您是如何解决项目部署在github上资源指向错误的问题的？

**Comment by walleeeee** [comment]
npm build出来的资源指向是绝对路径，部署在github上的时候要改成相对路径

**Comment by walleeeee** [comment]
把资源引用上的  "/static"前的 "／"去掉变成相对路径就可以了
----- 原始邮件 -----
发件人：Franck <notifications@github.com>
收件人：walleeeee/daily-zhihu <daily-zhihu@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[walleeeee/daily-zhihu]_请教一下，这个项目部署在github上的使用了代理么_(#1)
日期：2017年03月26日 03点48分

我尝试了将build后的项目部署在github上，不过部分静态资源指向有问题，在本地用tomcat或者nginx代理就不存在相应问题，我想请问您是如何解决项目部署在github上资源指向错误的问题的？

&mdash;
