### ISSUE TITLE
图片403禁止访问

### ISSUE THREAD

**Issue by AntsWang** [walleeeee/daily-zhihu#11]
参考着写的，文字可以显示，但是图片显示403禁止访问是因为什么啊

**Comment by walleeeee** [comment]
`<meta name="referrer" content="never"> `  这个设置了么

**Comment by AntsWang** [comment]
加上了，可以了，这个是什么作用啊

**Comment by walleeeee** [comment]
http协议中，如果从一个网页跳到另一个网页，http 头字段里面会带个 referer，图片服务器通过检测 referer 是否来自规定域名，来进行防盗链。如果没有 referer，服务器会认为是浏览器直接打开了文件，所以是可以显示的。

**Comment by AntsWang** [comment]
懂了，谢谢！
