### ISSUE TITLE
请教一下如何使用node.js进行二次封装解决跨域问题

### ISSUE THREAD

**Issue by werbhelius** [walleeeee/daily-zhihu#12]

**Comment by walleeeee** [comment]
[http://wiki.jikexueyuan.com/project/node-lessons/superagent-cheerio.html](url)

**Comment by werbhelius** [comment]
有一点概念不理解，是不是服务端去请求接口就不存在跨域的问题？跨域只是浏览器做的限制呢？

**Comment by walleeeee** [comment]
node是做中转，重新设置了服务器跨域权限，限制是在服务端做的
`app.get( "/get", function ( req, res, next ) {`
`	var api = req.query.api;`
`	superagent.get( 请求地址 + api ).end( function ( err, sres ) {`
`			if ( err ) {`
`				res.send( "☺" );`
`				return;`
`			}`
`			res.header( "Access-Control-Allow-Origin", "*" );//重新设置服务器跨域权限`
`			res.send( sres.text );`
`		} );`
`} );`
