### ISSUE TITLE
请教下，上拉加载有什么地方要配置么

### ISSUE THREAD

**Issue by WM520** [walleeeee/daily-zhihu#13]
我直接拿了你的infiniteScroll.vue和scroll.js，还需要在哪里做些配置呢，谢谢解答

**Comment by walleeeee** [comment]
没有什么需要配置的啊，你加载遇到什么问题了么

**Comment by WM520** [comment]
就是不调用loadMore方法，你有时间吗？帮我看看，谢谢

**Comment by WM520** [comment]
https://github.com/WM520/scroller1  这是我引用的你上拉组件项目，向上滑动不调用loadMore方法

**Comment by walleeeee** [comment]
就改了下Hello.vue
Hello.vue 的div加个‘test’的class
`
<style lang="css">
	.test{
    z-index: 1;
    width: 100vw;
    height: 100vh;
    overflow: auto;
    transition: transform 0.3s ease;
    -webkit-overflow-scrolling: touch;
	}
</style>
`

**Comment by WM520** [comment]
ni 你拿我的项目，就该了下hello.vue,就能实现上拉加载了吗，我没看懂你贴的代码，谢谢了，能说清楚点吗

**Comment by walleeeee** [comment]
加载组件外层的div也就是scroller应该是固定宽高 overflow: auto  这个样加载组件才能监听到scroller的滚动事件

**Comment by WM520** [comment]
ok了，感谢你，我是刚接触这行

**Comment by WM520** [comment]
可以加你个好友么

**Comment by walleeeee** [comment]
455678702
