### ISSUE TITLE
使用 keep-alive 关于滚动位置的问题

### ISSUE THREAD

**Issue by werbhelius** [walleeeee/daily-zhihu#14]
有一点没搞懂如何在返回上一个router的时候保存list滚动的位置
我自己照着你的写，back 后会默认定位到list初始位置
使用了 scrollBehavior 还是没有效果
感谢！希望可以帮助下我 😄

**Comment by walleeeee** [comment]
文章详情页返回到列表页都没有回到上次的位置么

**Comment by werbhelius** [comment]
可以了，感谢！是我用错了
