### ISSUE TITLE
是我脸黑才这样吗？

### ISSUE THREAD

**Issue by yuyeqianxun** [walleeeee/daily-zhihu#15]
![qq 20170525101700](https://cloud.githubusercontent.com/assets/17348438/26433110/36b5a23c-4133-11e7-9db8-ba5b9f06c2c1.jpg)
环境是win7；报错是
22 error zhihu@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the zhihu@1.0.0 dev script 'node build/dev-server.js'.

**Comment by walleeeee** [comment]
cnpm install 再npm run dev
