### ISSUE TITLE
bug反馈下

### ISSUE THREAD

**Issue by yuyeqianxun** [walleeeee/daily-zhihu#17]
![image](https://cloud.githubusercontent.com/assets/17348438/26777523/1f3546cc-4a10-11e7-88ac-2f1b8ce11f79.png)
菜单的active样式在按返回按钮的时候是不会变动的。比如说，按了**设计日报**，那一栏变黄了。当返回上一页时，比如说返回到**首页**了，变黄的那一栏任然是**设计日报**，并不会变成**首页**。

**Comment by walleeeee** [comment]
你是点的浏览器自带的返回吧

**Comment by walleeeee** [comment]
bug已经修复了
