### ISSUE TITLE
你好为什么我clone了你的项目 然后我安装了依赖以后 打不开 

### ISSUE THREAD

**Issue by yehoan** [walleeeee/daily-zhihu#2]

**Comment by walleeeee** [comment]
npm run dev  启动不了项目么？

**Comment by alexx617** [comment]
安装完依赖后会提示没有con.vue的文件的,你新建然后拷贝一下就好了,要学会看报错提示.

**Comment by chengwi** [comment]
为什么没有con.vue文件，而且新建不了

**Comment by walleeeee** [comment]
本地新建一下con.vue，从网页端拷贝一下con.vue的代码

**Comment by chengwi** [comment]
本地新建con.vue报错cannot create

**Comment by walleeeee** [comment]
你用编辑器在桌面新建一个con.vue再拷进去都不行？

**Comment by luo772435545** [comment]
页面显示cannot get /，请问这是为什么呢

**Comment by walleeeee** [comment]
控制台报什么错

**Comment by cxflag203** [comment]
这个是 win 系统的限制，windows 系统不允许创建名称为 con 的文件
