### ISSUE TITLE
npm install的时候报错了

### ISSUE THREAD

**Issue by ChenZhiKuan** [walleeeee/daily-zhihu#22]
![image](https://user-images.githubusercontent.com/15372877/31021314-09a93d78-a568-11e7-9c92-c8030adfcc6e.png)

**Comment by walleeeee** [comment]
cnpm 呢

**Comment by ChenZhiKuan** [comment]
可以了 但是我npm的时候开VPN和没开VPN都有试过

**Comment by ChenZhiKuan** [comment]
![default](https://user-images.githubusercontent.com/15372877/31045910-b8d3f2ee-a620-11e7-9068-b2cbf88b6787.GIF)


想请问下这个commit的第二个参数1是什么意思

**Comment by walleeeee** [comment]
返回顶部按钮显示隐藏

**Comment by ChenZhiKuan** [comment]
失策，被APP.vue那边那个toggle迷惑了
