### ISSUE TITLE
问一些问题

### ISSUE THREAD

**Issue by hw1995** [walleeeee/daily-zhihu#23]
在scroll.js中
watch: {
		scroller( scroller, oldScroller ) {
			if ( scroller === oldScroller ) return
			this.$unbindScroll( oldScroller )
			this.$bindScroll( scroller )
		}
	}
中的oldScroller从哪里来？

**Comment by walleeeee** [comment]
https://cn.vuejs.org/v2/api/#vm-watch

**Comment by hw1995** [comment]
OK,I Know.
This is a great test demo.
Thanks.
