### ISSUE TITLE
clone下载后，npm install后，本地运行没有错误，部署到服务器错误

### ISSUE THREAD

**Issue by lovefox666** [walleeeee/daily-zhihu#26]
本地运行http://localhost:8083可以运行正常，
但是部署到服务器时错误，
Failed to load resource: the server responded with a status of 404 ()
manifest.7477741344c67108b5d7.js:1 Failed to load resource: the server responded with a status of 404 ()
app.3f2dd1a7626b7193436e.js:1 Failed to load resource: the server responded with a status of 404 ()
vendor.ad15357dfbe42f9bd476.js:1 Failed to load resource: the server responded with a status of 404 ()
app.3f2dd1a7626b7193436e.js:1 Failed to load resource: the server responded with a status of 404 ()
app.0e31f34990a44256161c14ab2dc5aa86.css:1 Failed to load resource: the server responded with a status of 404 ()
我的首页路径是诸如：http://www.aaa.com/zhihu
是因为路径问题么？

**Comment by walleeeee** [comment]
npm build出来的资源指向是绝对路径，部署到服务器上的时候要改成相对路径
