### ISSUE TITLE
你好，项目无法启动

### ISSUE THREAD

**Issue by ToWorkit** [walleeeee/daily-zhihu#6]
ERROR  Failed to compile with 1 errors10:07:39

This relative module was not found:

* ./views/con in ./src/router.js
> Listening at http://localhost:8083

**Comment by walleeeee** [comment]
你文件解压的时候是不是就报错了

**Comment by walleeeee** [comment]
你解压的时候文件缺失了，在src/views下 新建一个 con.vue  去网页端拷贝一下con.vue的代码就好了

**Comment by ToWorkit** [comment]
好的，谢谢
